### ISSUE TITLE
How can I compile gloo with openmpi?

### ISSUE THREAD

**Issue by thzhao** [facebookincubator/gloo#103]
Hi, I want to use mpi run jobs across machines.  I use compile gloo with 
cmake ../ -DBUILD_TEST=1 -DBUILD_BENCHMARK=1 -USE_MPI=ON

but It didn't compile the mpi directory. I checked the cmake file, and it seems no USE_MPI flag.

How can I build gloo with mpi?

**Comment by pietern** [comment]
Hi, you have to pass `-DUSE_MPI=ON`, not just `-USE_MPI=ON`. Can you post the output of cmake?

**Comment by thzhao** [comment]
thanks for your help. It worked when I passed the -DUSE_MPI=ON. I already installed the gloo lib in  /usr/local/lib/. 
I have another question that how I can compile the main_managed.cc example in MPI directory. I try to use mpic++ compile directly, but it failed.

I want to use mpi to run gloo jobs Instead of rendezvous. How can I use it?

Thanks

**Comment by thzhao** [comment]
here is my complier output.
$mpic++ -std=c++11 -o ex main_unmanaged.cc

/tmp/ccStq6ou.o: In function `main':
main_unmanaged.cc:(.text+0x1ab): undefined reference to `gloo::transport::tcp::CreateDevice(gloo::transport::tcp::attr const&)'
main_unmanaged.cc:(.text+0x1ff): undefined reference to `gloo::mpi::Context::connectFullMesh(std::shared_ptr<gloo::transport::Device>&)'
/tmp/ccStq6ou.o: In function `gloo::AllreduceRing<int>::AllreduceRing(std::shared_ptr<gloo::Context> const&, std::vector<int*, std::allocator<int*> > const&, int, gloo::ReductionFunction<int> const*)':
main_unmanaged.cc:(.text._ZN4gloo13AllreduceRingIiEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE[_ZN4gloo13AllreduceRingIiEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE]+0x37): undefined reference to `gloo::Algorithm::Algorithm(std::shared_ptr<gloo::Context> const&)'
main_unmanaged.cc:(.text._ZN4gloo13AllreduceRingIiEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE[_ZN4gloo13AllreduceRingIiEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE]+0x119): undefined reference to `gloo::Algorithm::getLeftPair()'
main_unmanaged.cc:(.text._ZN4gloo13AllreduceRingIiEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE[_ZN4gloo13AllreduceRingIiEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE]+0x129): undefined reference to `gloo::Algorithm::getRightPair()'
main_unmanaged.cc:(.text._ZN4gloo13AllreduceRingIiEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE[_ZN4gloo13AllreduceRingIiEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE]+0x14a): undefined reference to `gloo::Context::nextSlot(int)'
main_unmanaged.cc:(.text._ZN4gloo13AllreduceRingIiEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE[_ZN4gloo13AllreduceRingIiEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE]+0x220): undefined reference to `gloo::Context::nextSlot(int)'
main_unmanaged.cc:(.text._ZN4gloo13AllreduceRingIiEC2ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE[_ZN4gloo13AllreduceRingIiEC5ERKSt10shared_ptrINS_7ContextEERKSt6vectorIPiSaIS8_EEiPKNS_17ReductionFunctionIiEE]+0x331): undefined reference to `gloo::Algorithm::~Algorithm()'
/tmp/ccStq6ou.o: In function `gloo::AllreduceRing<int>::~AllreduceRing()':
main_unmanaged.cc:(.text._ZN4gloo13AllreduceRingIiED2Ev[_ZN4gloo13AllreduceRingIiED5Ev]+0xa9): undefined reference to `gloo::Algorithm::~Algorithm()'
/tmp/ccStq6ou.o: In function `_ZN9__gnu_cxx13new_allocatorIN4gloo3mpi7ContextEE9constructIS3_IP19ompi_communicator_tEEEvPT_DpOT0_':
main_unmanaged.cc:(.text._ZN9__gnu_cxx13new_allocatorIN4gloo3mpi7ContextEE9constructIS3_IP19ompi_communicator_tEEEvPT_DpOT0_[_ZN9__gnu_cxx13new_allocatorIN4gloo3mpi7ContextEE9constructIS3_IP19ompi_communicator_tEEEvPT_DpOT0_]+0x48): undefined reference to `gloo::mpi::Context::Context(ompi_communicator_t* const&)'
collect2: error: ld returned 1 exit status

and I checked the libgloo.a. It seems ok.

[  3%] Building CXX object third-party/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
Linking CXX static library libgtest.a
[  3%] Built target gtest
[  6%] Building CXX object third-party/googletest/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
Linking CXX static library libgtest_main.a
[  6%] Built target gtest_main
[  9%] Building CXX object gloo/CMakeFiles/gloo.dir/algorithm.cc.o
[ 12%] Building CXX object gloo/CMakeFiles/gloo.dir/allreduce_local.cc.o
[ 15%] Building CXX object gloo/CMakeFiles/gloo.dir/context.cc.o
[ 18%] Building CXX object gloo/CMakeFiles/gloo.dir/common/linux.cc.o
[ 21%] Building CXX object gloo/CMakeFiles/gloo.dir/common/logging.cc.o
[ 25%] Building CXX object gloo/CMakeFiles/gloo.dir/mpi/context.cc.o
[ 28%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/context.cc.o
[ 31%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/file_store.cc.o
[ 34%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/hash_store.cc.o
[ 37%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/prefix_store.cc.o
[ 40%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/store.cc.o
[ 43%] Building CXX object gloo/CMakeFiles/gloo.dir/rendezvous/redis_store.cc.o
[ 46%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/address.cc.o
[ 50%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/buffer.cc.o
[ 53%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/device.cc.o
[ 56%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/pair.cc.o
[ 59%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/address.cc.o
[ 62%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/buffer.cc.o
[ 65%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/device.cc.o
[ 68%] Building CXX object gloo/CMakeFiles/gloo.dir/transport/tcp/pair.cc.o
Linking CXX static library libgloo.a
[ 68%] Built target gloo
[ 71%] Building CXX object gloo/CMakeFiles/gloo_builder.dir/allreduce_builder.cc.o
Linking CXX static library libgloo_builder.a
[ 71%] Built target gloo_builder
[ 75%] Building CXX object gloo/test/CMakeFiles/test.dir/allreduce_builder_test.cc.o
[ 78%] Building CXX object gloo/test/CMakeFiles/test.dir/allreduce_test.cc.o
[ 81%] Building CXX object gloo/test/CMakeFiles/test.dir/barrier_test.cc.o
[ 84%] Building CXX object gloo/test/CMakeFiles/test.dir/broadcast_test.cc.o
[ 87%] Building CXX object gloo/test/CMakeFiles/test.dir/linux_test.cc.o
[ 90%] Building CXX object gloo/test/CMakeFiles/test.dir/main.cc.o
Linking CXX executable test
[ 90%] Built target test
[ 93%] Building CXX object gloo/benchmark/CMakeFiles/benchmark.dir/main.cc.o
[ 96%] Building CXX object gloo/benchmark/CMakeFiles/benchmark.dir/options.cc.o
[100%] Building CXX object gloo/benchmark/CMakeFiles/benchmark.dir/runner.cc.o
Linking CXX executable benchmark
[100%] Built target benchmark

ar -t libgloo.a

algorithm.cc.o
allreduce_local.cc.o
context.cc.o
linux.cc.o
logging.cc.o
context.cc.o
context.cc.o
file_store.cc.o
hash_store.cc.o
prefix_store.cc.o
store.cc.o
redis_store.cc.o
address.cc.o
buffer.cc.o
device.cc.o
pair.cc.o
address.cc.o
buffer.cc.o
device.cc.o
pair.cc.o

**Comment by pietern** [comment]
Perhaps it is picking up an earlier install you did (you mentioned you installed it to /usr/local before). Since it's a static library you can try passing the full path to mpic++. I have never used mpic++ so don't know about its peculiarities.

**Comment by pietern** [comment]
@thzhao Did you also try specifying the static library by path instead of with `-lgloo`?

**Comment by pietern** [comment]
Closing this issue due to timeout.
