### ISSUE TITLE
I got "cmake fail".

### ISSUE THREAD

**Issue by andrew-yang0722** [facebookincubator/gloo#104]
$ cmake ../ -DBUILD_TEST=1 -DBUILD_BENCHMARK=1

```
CMake Error at gloo/CMakeLists.txt:122 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
```

I found error the message at "CMakeFiles/CMakeError.log"

CMakeFiles/cmTC_70939.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_70939.dir/build.make:97: recipe for target 'cmTC_70939' failed
make[1]: *** [cmTC_70939] Error 1
make[1]: Leaving directory '/disk3/daum/release/gloo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_70939/fast' failed

Linking C executable cmTC_562bd
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_562bd.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_562bd.dir/CheckFunctionExists.c.o  -o cmTC_562bd -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_562bd.dir/build.make:97: recipe for target 'cmTC_562bd' failed
make[1]: *** [cmTC_562bd] Error 1
make[1]: Leaving directory '/disk3/daum/release/gloo/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_562bd/fast' failed
make: *** [cmTC_562bd/fast] Error 2

**Comment by pietern** [comment]
Thanks for the report. Fix is merged.
