### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by boriskovalev** [facebookincubator/gloo#110]
When I run a following command:

cmake ../ -DBUILD_TEST=1 -DBUILD_BENCHMARK=1 -DUSE_IBVERBS_DEFAULT=ON -DUSE_CUDA=1 && make

I have an issue:
~/gloo/build# cmake ../ -DBUILD_TEST=1 -DBUILD_BENCHMARK=1 -DUSE_IBVERBS_DEFAULT=ON -DUSE_CUDA=1 && make
-- Build type not set -- defaulting to Release                                                                          
-- CUDA detected: 8.0                                                                                                   
-- Added CUDA NVCC flags for: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61                                                       
-- Found libcuda: /usr/local/cuda-8.0/lib64/stubs/libcuda.so                                                            
-- Found libnvrtc: /usr/local/cuda-8.0/lib64/libnvrtc.so                                                                
CMake Warning (dev) at gloo/test/CMakeLists.txt:11 (add_executable):                                                    
  Policy CMP0037 is not set: Target names should not be reserved and should                                             
  match a validity pattern.  Run "cmake --help-policy CMP0037" for policy                                               
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /root/gloo/build
[  3%] Built target gtest
[  6%] Built target gtest_main
[ 45%] Built target gloo
[ 58%] Built target gloo_cuda
[ 62%] Built target gloo_builder
[ 75%] Built target test
[ 87%] Built target test_cuda
[ 88%] Building CXX object gloo/benchmark/CMakeFiles/benchmark.dir/runner.cc.o
/root/gloo/gloo/benchmark/runner.cc: In member function â€˜void gloo::benchmark::Runner::rendezvousFileSystem()â€™:
/root/gloo/gloo/benchmark/runner.cc:171:3: error: â€˜PrefixStoreâ€™ is not a member of â€˜gloo::rendezvousâ€™
   rendezvous::PrefixStore prefixStore(options_.prefix, fileStore);
   ^
/root/gloo/gloo/benchmark/runner.cc:174:35: error: â€˜prefixStoreâ€™ was not declared in this scope
   backingContext->connectFullMesh(prefixStore, transportDevices_.front());
                                   ^
/root/gloo/gloo/benchmark/runner.cc: In member function â€˜void gloo::benchmark::Runner::run(gloo::benchmark::Runner::BenchmarkFn<T>&, int)â€™:
/root/gloo/gloo/benchmark/runner.cc:253:19: warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
       auto fn = [&benchmark = benchmarks[i]] { benchmark->run(); };
                   ^
/root/gloo/gloo/benchmark/runner.cc:281:17: warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
     auto fn = [&benchmark = benchmarks[i]] { benchmark->run(); };
                 ^
gloo/benchmark/CMakeFiles/benchmark.dir/build.make:110: recipe for target 'gloo/benchmark/CMakeFiles/benchmark.dir/runner.cc.o' failed
make[2]: *** [gloo/benchmark/CMakeFiles/benchmark.dir/runner.cc.o] Error 1
CMakeFiles/Makefile2:561: recipe for target 'gloo/benchmark/CMakeFiles/benchmark.dir/all' failed
make[1]: *** [gloo/benchmark/CMakeFiles/benchmark.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

How I can solve it ?

Thanks

**Comment by pietern** [comment]
Thanks for reporting @boriskovalev!

I made a mistake in 03833bbfab290af01b3e9ea3e819ce53471fe082 by not including `prefix_store.h` by default. Fix is in #111.

**Comment by pietern** [comment]
This is now merged -- see bb3c56c7b3963fd98c034b0d0d8f1eb709188dcf.
