### ISSUE TITLE
Can`t Compile gloo on a 32-bit system

### ISSUE THREAD

**Issue by Mohamedemad4** [facebookincubator/gloo#115]
the issue is straightforward I need Pytorch on a raspberryPi and pytroch requires gloo which can only be compiled on a 64-bit system, So how can I override this Please Help

**Comment by pietern** [comment]
Can you disable gloo from your pytorch build? I'm sure there is some CMake option to do so.

32-bit support for Gloo is not planned and don't think ever will be. In Caffe2/PyTorch is it only used for training models, which generally happens on beefy machines and not RPi's.
