### ISSUE TITLE
ProcessGroupGloo RuntimeError: Wait timeout

### ISSUE THREAD

**Issue by forhonourlx** [facebookincubator/gloo#148]
When I was trying: "pytorch.distributed.init_process_group(rank=0,backend="gloo",init_method='file:///home/simon/Desktop/shared_folder/gloo_shared_file',world_size=2)", "RuntimeError: Wait timeout" came out.
The above path is a shared folder on Ubuntu and samba, it works well.
gloo_shared_file is found and found.

Traceback (most recent call last):
File "/home/simon/Desktop/dist_rl/dist_rl.py", line 13, in
dist.init_process_group(rank=0,backend="gloo",init_method='file:///home/simon/Desktop/shared_folder/gloo_shared_file',world_size=2)
File "/home/simon/anaconda3/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 283, in init_process_group
_default_pg = ProcessGroupGloo(store, rank, world_size)
RuntimeError: Wait timeout

Could somebody give me a hand? Thanks indeed.

**Comment by pietern** [comment]
Hi! This issue is related to PyTorch and not Gloo specifically. Please keep this in mind for future issues you might encounter. Do you run the same process on two machines, both specifying the same path, and different rank? This is not clear to me from your post.

**Comment by pietern** [comment]
This is a dup of pytorch/pytorch#13583. Please don't cross post.
