### ISSUE TITLE
Consider changing license

### ISSUE THREAD

**Issue by liamuk** [facebookincubator/gloo#153]
A lot of companies (such as mine) have reservations with the BSD+Patents license that gloo is currently licensed under.

A lot of Facebook projects, for example RocksDB and React, have changed from this license to others, like Apache 2.0 or MIT as as a result of this issue. 

Would it be possible for gloo to do the same?

Some further reading:
- https://github.com/facebook/react/issues/10191
- https://news.ycombinator.com/item?id=14779881

**Comment by pietern** [comment]
Thanks for bringing this up. I think it should be possible. I'll update here when I can.

**Comment by pietern** [comment]
@liamuk Thanks again for bringing this up. This is now done.

**Comment by liamuk** [comment]
Thanks :)
