### ISSUE TITLE
Error with world size of 1 (in Pytorch 1.0)

### ISSUE THREAD

**Issue by Kh4L** [facebookincubator/gloo#154]
Hi,
I was trying Pytorch 1.0 with `torch.distributed` and with different backend and configs.
MPI and NCCL work fine with different world size.

I encountered an error in when using Gloo allreduce with world size of 1:

```
RuntimeError: [enforce fail at /pytorch/third_party/gloo/gloo/allreduce.cc:37] context->getPair(recvRank). missing connection between rank 0 (thisprocess) and rank 0
```
Here is the command line:
```
mkdir -p /tmp/com_file && python3 main.py --init-method 'file:///tmp/com_file/shared_file' --backend gloo --rank 0 --world-size 1
```
The script I am using:
https://github.com/Kh4L/pytorch-distributed-example/blob/master/mnist/main.py

I am not sure if I should open an issue here or on pytorch repo, but let's try here.
Thank you

**Comment by pietern** [comment]
Hi! Thanks for opening the issue.

I agree it would be convenient to use these collectives even if you're not running anything distributed across multiple processes. This is not explicitly tested and therefore not yet supported. It shouldn't be hard to support this and I'll look into it shortly.

**Comment by pietern** [comment]
FYI, the gloo submodule still needs to be bumped in the pytorch repository for this to work.
