### ISSUE TITLE
fatal error: 'malloc.h' file not found

### ISSUE THREAD

**Issue by Oo121oO** [facebookincubator/gloo#163]
bogon:build ouyangshaocong$ make
[  3%] Building CXX object gloo/CMakeFiles/gloo.dir/algorithm.cc.o
In file included from /Users/ouyangshaocong/gloo/gloo/algorithm.cc:9:
In file included from /Users/ouyangshaocong/gloo/gloo/algorithm.h:14:
In file included from /Users/ouyangshaocong/gloo/gloo/math.h:11:
In file included from /Users/ouyangshaocong/gloo/gloo/types.h:26:
/Users/ouyangshaocong/gloo/gloo/common/common.h:12:10: fatal error: 'malloc.h'
      file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [gloo/CMakeFiles/gloo.dir/algorithm.cc.o] Error 1
make[1]: *** [gloo/CMakeFiles/gloo.dir/all] Error 2
make: *** [all] Error 2

pls help me out, thx.

after I change malloc.h to sys/malloc.h, function memalign() was not found.

**Comment by pietern** [comment]
Which version of glibc are you using?

This was added to support memalign on older versions of glibc in favor of using aligned_alloc.

See https://github.com/facebookincubator/gloo/pull/63 for more information.

**Comment by pietern** [comment]
No updates, closing the issue. Feel free to reopen if you have additional information.
