### ISSUE TITLE
Will gloo support Windows10?

### ISSUE THREAD

**Issue by hazelnutsgz** [facebookincubator/gloo#170]

**Comment by pietern** [comment]
This is not a goal.

Enabling Windows support for host side buffers should be possible and all changes should be isolated to `gloo/transport/tcp`, if you want to take a stab at it. The current I/O multiplexing is Linux specific (it uses epoll).

**Comment by pietern** [comment]
Can you tell more about where/how you would want to use Gloo?

**Comment by hazelnutsgz** [comment]
My situation is, 
We have two servers(Windows Server2019) connect with each other by ssh, each of which is equipped with one Nvidia GPU. 

My goal is,
training a CNN model leveraging two GPUs, at the assistance of gloo library.


My concern is,
whether gloo would be a good fit, only is there any alternatives?

**Comment by pietern** [comment]
I would try to use some MPI distribution instead. As I mentioned, Gloo doesn't support Windows and this is not planned, so you'll have to find something else. I believe NCCL doesn't support Windows either. If you're using PyTorch, the only other option is to try and use MPI.
