### ISSUE TITLE
Build error - gtest viable conversion error

### ISSUE THREAD

**Issue by mpruthvikumar** [facebookincubator/gloo#175]
Hi,
When I try to build the gloo, I get below error on Ubuntu 16.04
- have the latest gtest lib built

In file included from /root/gloo/gloo/test/broadcast_test.cc:15:
In file included from /root/gloo/gloo/test/base_test.h:11:
In file included from /usr/include/gtest/gtest.h:62:
In file included from /usr/include/gtest/gtest-param-test.h:193:
/usr/include/gtest/internal/gtest-param-util-generated.h:82:47: error: no viable conversion from returned value of type 'ParamGenerator<typename ::testing::internal::IteratorTraits<const int
      *>::value_type>' to function return type 'ParamGenerator<unsigned long>'
  operator ParamGenerator<T>() const { return ValuesIn(&v1_, &v1_ + 1); }
                                              ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/gtest/internal/gtest-param-util-generated.h:4893:42: note: in instantiation of function template specialization 'testing::internal::ValueArray1<int>::operator ParamGenerator<unsigned long>'
      requested here
        static_cast<ParamGenerator<T3> >(g3_),

**Comment by pietern** [comment]
Hi! Which version of gtest do you have installed on your system? It's picking up `/usr/include/gtest/gtest.h`.

**Comment by mpruthvikumar** [comment]
Hi,

I installed gtest

#sudo apt-get install libgtest-dev
and it is picked up at /usr/include/gtest/gtest.h

do you suggest to build googletest from source to the get the latest? or any other alternative?

**Comment by mpruthvikumar** [comment]
I have the version 
-->libgtest-dev/xenial,now 1.7.0-4ubuntu1 amd64 [installed]

My bad, it isnt the latest.

**Comment by mpruthvikumar** [comment]
@pietern,

Thank you for the comment. 
I updated to latest googletest and I am able to build

**Comment by pietern** [comment]
Great! Thanks for confirming.
