### ISSUE TITLE
Mac OS Support?

### ISSUE THREAD

**Issue by tgaddair** [facebookincubator/gloo#182]
Looks like Gloo does not play nice with Mac OS.  When I attempt to install:

```
In file included from gloo/gloo/algorithm.cc:9:
In file included from gloo/gloo/algorithm.h:14:
In file included from gloo/gloo/math.h:11:
In file included from gloo/gloo/types.h:26:
gloo/gloo/common/common.h:12:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
```

There are [suggestions](https://stackoverflow.com/questions/12973311/difference-between-stdlib-h-and-malloc-h) online to use stdlib.h instead for cross-platform support, as malloc.h is allegedly deprecated.  

Any chance Gloo can be made compatible with Mac OS?

**Comment by pietern** [comment]
Hi @tgaddair! Thanks for posting the issue. Currently there is no macOS support. The `malloc.h` error is probably easy to fix, but there is a larger problem with the dependency on `epoll(2)` for the TCP transport. I don't think it would be a lot of work to make it work with `kqueue` as well, but it's work nonetheless.

I'd be happy to take a look at this later this week.

**Comment by tgaddair** [comment]
Thanks @pietern!  We're looking forward to it.

**Comment by pietern** [comment]
@tgaddair It's gotten a bit later, but want to share an update. I'm working on a new transport implementation that uses libuv instead of using sockets directly. This should take care of any cross platform concerns. I expect this to take a couple more days.

**Comment by tgaddair** [comment]
Hey @tgaddair, thanks for the response!  Any update on the new transport implementation?  

We recently shipped Gloo support for Horovod by the way, and so far it's working very well as an alternative to MPI!

**Comment by pietern** [comment]
Glad to hear it's working well so far!

There is a stack of tiny changes at #206 (see linked PRs) to make Gloo compile on macOS and then a work in progress PR for a libuv transport at #195. It already works, and you can give it a try if you stack it on top of the set of fixes, but there's still some work to do to filter out some tests and make it work with the benchmark tool.

**Comment by pietern** [comment]
This is now merged.
