### ISSUE TITLE
Load balancing across multiple TCP network interfaces

### ISSUE THREAD

**Issue by tgaddair** [facebookincubator/gloo#183]
Open MPI supports using [multiple network interfaces](https://www.open-mpi.org/faq/?category=tcp#tcp-selection) at once for the purpose of load balancing TCP communication across them.  

Looking at the [code](https://github.com/facebookincubator/gloo/blob/master/gloo/transport/tcp/device.h#L31) it appears that Gloo will only accept a single network interface, is this correct?  If so, can support for multiple interfaces be implemented?

**Comment by pietern** [comment]
Thanks for bringing up the issue. It can't automatically load balance over multiple devices (i.e. round robin the send/recv operations). To do this you'd have to create multiple contexts, one per device, and round robin on the collective dispatch.

**Comment by pietern** [comment]
I created #190 to track.

We do something similar in PyTorch upstream, but it would be better suited to live in Gloo.
