### ISSUE TITLE
Any plan for supporting BSD platform?

### ISSUE THREAD

**Issue by KnightBaron** [facebookincubator/gloo#187]
I'm trying to compile Gloo on a BSD platform. However, it seems that Gloo rely on many Linux headers. Is there any plan to support BSD?

**Comment by pietern** [comment]
Hi @KnightBaron -- there's no plans for BSD support.

There are however plans to support for macOS for easier development (see #182).

If I might ask, what are you running on BSD where you'd like to use Gloo?

**Comment by KnightBaron** [comment]
Hello @pietern 

Thank you for the response. I'm working on a distributed DNN training solution for an undisclosed proprietary BSD-based platform.

By the way, I managed to get Gloo running on the platform by removing IB and CUDA capability. Unfortunately, our policy prevent me from contributing the code back. :(

**Comment by pietern** [comment]
That's too bad. I'm glad you got it working.

I'll close this issue since you got it working, and we have #182 for the macOS / BSD support.
