### ISSUE TITLE
Running operations with size=1

### ISSUE THREAD

**Issue by tgaddair** [facebookincubator/gloo#209]
I saw that support was added a while back for running allreduce when the world size is 1 ([PR](https://github.com/facebookincubator/gloo/commit/376f632e75642dfe98736e56b3eb6e4b61755b35)).  But there still seems to be a number of operations that do not work in this degenerate case, including allgather:

```
Wed Aug 14 16:00:50 2019[0]<stderr>:terminate called after throwing an instance of 'gloo::EnforceNotMet'
Wed Aug 14 16:00:50 2019[0]<stderr>:  what():  [enforce fail at horovod/third_party/gloo/gloo/allgather.cc:31] context->getPair(recvRank). missing connection between rank 0 (this process) and rank 0
Wed Aug 14 16:00:50 2019[0]<stderr>:Aborted
Process 0 exit with status code 134
```

For context, this is important for running Horovod, because the user will often want to test that their code works running as a single process before scaling up to multiple processes.  We could theoretically work around this by adding special handling of the size=1 case to Horovod, but that makes the control flow more difficult to reason about.

Any chance all ops can be changed to support running with size=1?

**Comment by pietern** [comment]
Hey @tgaddair, sure that shouldn't be hard. Do you mind submitting a PR for it?

**Comment by tgaddair** [comment]
Hey @pietern, does #189 resolve this issue?

**Comment by pietern** [comment]
It might! I figured since this was a new issue you were already using a version after that fix.

**Comment by tgaddair** [comment]
Ah, sorry.  We were pinned to a version back in May.  Will try the latest and see how it goes!

**Comment by tgaddair** [comment]
Just ran a test with the latest Gloo.  Everything looks good when world size is 1.  So I'll go ahead and close this.  Thanks for bearing with me!

**Comment by pietern** [comment]
@tgaddair Thanks for confirming.
