### ISSUE TITLE
Running benchmark Error: reply->type == REDIS_REPLY_INTEGER. 6 vs 3

### ISSUE THREAD

**Issue by linquanxu** [facebookincubator/gloo#21]
Dear All,
When I used the command as a following,
./benchmark --size 2 --rank 0 --redis-host 172.16.18.218 --redis-port 7000 --prefix 152 --transport tcp --elements 1000 --iteration-time 1s allreduce_ring_chunked

There was an error with ' what():  [enforce fail at /home/xulinquan/gloo/gloo/rendezvous/redis_store.cc:92] reply->type == REDIS_REPLY_INTEGER. 6 vs 3'.
How to fix this error?

PS: 
The version of Redis is 3.2.8
 I used two machines(172.16.18.216, 172.16.18.218).  
On the machine(172.16.18.218), I start up 3 nodes，7000, 7001, 7002, respectively.  
On the anther machine(172.16.18.216), I also start up 3 nodes, 7003,7004,7005,respectively. 
1） start the server：  redis-server redis.conf
xulinquan@root0-SCW4350-216:~/redis/7005$ ps -ef|grep redis
xulinqu+  6779     1  0 15:40 ?        00:00:00 redis-server 172.16.18.216:7003 [cluster]
xulinqu+  6788     1  0 15:40 ?        00:00:00 redis-server 172.16.18.216:7004 [cluster]
xulinqu+  6808     1  0 15:41 ?        00:00:00 redis-server 172.16.18.216:7005 [cluster]
xulinquan@root0-PR4764GW-218:~/redis$ ps aufx|grep redis
xulinqu+ 11128  0.0  0.0  15944  2604 pts/30   S+   15:43   0:00          \_ grep --color=auto redis
xulinqu+ 11114  0.0  0.0  40452  9236 ?        Ssl  15:43   0:00 redis-server 172.16.18.218:7001 [cluster]
xulinqu+ 11118  0.0  0.0  40452  9224 ?        Ssl  15:43   0:00 redis-server 172.16.18.218:7000 [cluster]
xulinqu+ 11122  0.0  0.0  40452  9128 ?        Ssl  15:43   0:00 redis-server 172.16.18.218:7002 [cluster]

2）Created the cluster 
xulinquan@root0-PR4764GW-218:~/redis$ ./redis-trib.rb create --replicas 1 172.16.18.218:7000 172.16.18.218:7001 172.16.18.218:7002 172.16.18.216:7003 172.16.18.216:7004 172.16.18.216:7005
>>> Creating cluster
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
172.16.18.218:7000
172.16.18.216:7003
172.16.18.218:7001
Adding replica 172.16.18.216:7004 to 172.16.18.218:7000
Adding replica 172.16.18.218:7002 to 172.16.18.216:7003
Adding replica 172.16.18.216:7005 to 172.16.18.218:7001
M: 9f83308678f8bcf9e8c2faa7d0882689963d2276 172.16.18.218:7000
   slots:0-5460 (5461 slots) master
M: 46e379a567b4f6ec5d84114973141b5a7a7bb966 172.16.18.218:7001
   slots:10923-16383 (5461 slots) master
S: 37c102a7b6d6004ccce69d74ca2f62ef93eaa1d9 172.16.18.218:7002
   replicates f656bcb8bb63b8384bc3d2cdde07feb34850e2bc
M: f656bcb8bb63b8384bc3d2cdde07feb34850e2bc 172.16.18.216:7003
   slots:5461-10922 (5462 slots) master
S: 4fcaad8fb6481267ce58581f4b2f8ec0fe70bcf8 172.16.18.216:7004
   replicates 9f83308678f8bcf9e8c2faa7d0882689963d2276
S: 06571f35518f4eb4570d2a49f0cf23d4681e6c09 172.16.18.216:7005
   replicates 46e379a567b4f6ec5d84114973141b5a7a7bb966
Can I set the above configuration? (type 'yes' to accept): yes
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join....
>>> Performing Cluster Check (using node 172.16.18.218:7000)
M: 9f83308678f8bcf9e8c2faa7d0882689963d2276 172.16.18.218:7000
   slots:0-5460 (5461 slots) master
   1 additional replica(s)
S: 4fcaad8fb6481267ce58581f4b2f8ec0fe70bcf8 172.16.18.216:7004
   slots: (0 slots) slave
   replicates 9f83308678f8bcf9e8c2faa7d0882689963d2276
S: 06571f35518f4eb4570d2a49f0cf23d4681e6c09 172.16.18.216:7005
   slots: (0 slots) slave
   replicates 46e379a567b4f6ec5d84114973141b5a7a7bb966
M: 46e379a567b4f6ec5d84114973141b5a7a7bb966 172.16.18.218:7001
   slots:10923-16383 (5461 slots) master
   1 additional replica(s)
M: f656bcb8bb63b8384bc3d2cdde07feb34850e2bc 172.16.18.216:7003
   slots:5461-10922 (5462 slots) master
   1 additional replica(s)
S: 37c102a7b6d6004ccce69d74ca2f62ef93eaa1d9 172.16.18.218:7002
   slots: (0 slots) slave
   replicates f656bcb8bb63b8384bc3d2cdde07feb34850e2bc
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
xulinquan@root0-PR4764GW-218:~/redis$ 

Is there anyone who knows how to configure the Redis for testing the benchmark? With grateful.

**Comment by pietern** [comment]
Hi @linquanxu, there's no need to run Redis cluster to run the benchmark. Just start a single instance and point the benchmark tool there.

**Comment by linquanxu** [comment]
@pietern Thanks to your reply. I start a single instance using the machine(172.16.18.218) and run the following command: 

On the machine(172.16.18.218),
 ./benchmark --size 2 --rank 0 --redis-host 172.16.18.218 --redis-port 7000 --prefix 1223 --transport tcp --elements 10 --iteration-time 1s allreduce_ring_chunked.
On the machine (172.16.18.216), 
./benchmark --size 2 --rank 1 --redis-host 172.16.18.218 --redis-port 7000 --prefix 1223 --transport tcp --elements 10 --iteration-time 1s allreduce_ring_chunked.

There was another error,
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/xulinquan/gloo/gloo/rendezvous/redis_store.cc:52] reply->integer == 1. 0 vs 1. Key '1223-0/1/0' already set
Aborted (core dumped)

I don't know what's going on. Could you help me fix this issue?

**Comment by pietern** [comment]
The prefix needs to be unique for every run, so instead of passing --prefix 1223, you should pass some unique identifier. The identifier needs to be identical for all processes participating in a benchmark run.

**Comment by linquanxu** [comment]
@pietern  I set the --prefix is 1224. However, I don't receive any responses from the machine.
![Uploading image.png…]()
how to fix this issue?

**Comment by linquanxu** [comment]
I set the --prefix = 1224. However, I don't receive any responses from the machine.
![a](https://cloud.githubusercontent.com/assets/16631303/24738660/b82cd1ae-1ac9-11e7-868a-b2720097cd6e.png)

how to fix this issue?

**Comment by pietern** [comment]
Did you run both benchmark processes (on each machine) with the prefix 1224?

**Comment by linquanxu** [comment]
Thanks, @pietern  Yes, On the machine (172.16.18,218), I start a Redis server and run a Benchmark process.
redis-server redis.conf & ./benchmark --size 2 --rank 0 --redis-host 172.16.18.218 --redis-port 7000 --prefix 1223 --transport tcp --elements 10 --iteration-time 1s allreduce_ring_chunked

Meanwhile,
On the other machine(172,16.18.216),
./benchmark --size 2 --rank 1 --redis-host 172.16.18.218 --redis-port 7000 --prefix 1224 --transport tcp --elements 10 --iteration-time 1s allreduce_ring_chunked

**Comment by pietern** [comment]
Do these hosts by any chance have multiple network interfaces?

The benchmark tool uses the hostname to resolve an IP address to bind to. If this resolves to the external IP address of the machine, then it is possible they are not able to connect. If you can confirm, I can whip up a fix so you can pass an extra argument to the benchmark tool which IP address to use.

**Comment by linquanxu** [comment]
@pietern  Thanks for your quick response.
Here are the network interfaces：
![Uploading a.png…]()

![Uploading b.png…]()

**Comment by pietern** [comment]
Thanks for posting the information.

There's a few changes incoming that will print the address used by the benchmark that should help us debug this. I suspect the hostname of the machines don't resolve to the 172.16.18.* addresses you're trying to use. Can you run a ping of root0-PR47-GW-218 and see what the resolved IP address is? I suspect this is different from the 172.16.18.* addresses...

**Comment by linquanxu** [comment]
@pietern  Thank for your for your suggestion. I run a ping of hostname as a flowing:
![image](https://cloud.githubusercontent.com/assets/16631303/24844686/13217674-1ddf-11e7-814d-3268f169b668.png)

![image](https://cloud.githubusercontent.com/assets/16631303/24844729/537661c6-1ddf-11e7-8ce7-bf80f144321a.png)

However, the error is the same as above.

**Comment by pietern** [comment]
Sure, I didn't expect this to fix it, just give more information.

Can you run ping for 218 on the 218 machine? I suspect that doesn't show the 218 IP addres...

**Comment by pietern** [comment]
By the way, the latest changes in the repository will display some information about the outgoing interface and IP address when you run it. I suspect it shows that it doesn't use the 218 IP address/network interface, which in turn means the hosts can't connect to each other.

**Comment by linquanxu** [comment]
@pietern  I really appreciate you give me so much help. This error has been fixed.
I commented out this configuration in the host file.
![image](https://cloud.githubusercontent.com/assets/16631303/24860363/ca4035b0-1e26-11e7-8a48-6e0a96e46cfb.png)

My example output:
elements   min (us)   p50 (us)   p99 (us)   max (us)    samples
1        290        422        491        566       2762
10        302        438        505        563       2555
100        331        460        521        588       2269
1000        485        672        793        836       1713
 10000        878       1213       1416       1561        824
100000       4191       4551       4660       4843        196
1000000      35348      35527      35781      36144         28
5000000     171367     171547     176922     176922          5

There are some questions:
1)	This result is worse than your experimental results, I would like to ask this result is correct?
The speed of eth0 I used is 1000Mb/s.
![image](https://cloud.githubusercontent.com/assets/16631303/24860391/f19084a8-1e26-11e7-83fa-89d4c27b083d.png)
2)	Are your experimental results running on the machines with a 40GbE network?
3)	What the meaning of parameter with  --iteration-time 1s?

**Comment by pietern** [comment]
@linquanxu No problem, happy to help, and thank you for posting the issue! It means we both help to make sure we fix underlying problems and show the right data so it is easier for other people to use.

Great that you got it to work! I see that you're using the latest code and it now shows the little header before the benchmark output with transport details. This now includes the IP address, so it would have printed '127.0.0.1' in your case, helping us debug the problem faster.

Re: your questions:

1. It looks about right. With 1Gb/sec you have a theoretical maximum of 125MB/sec. Subtract some overhead and you get to 110MB/sec. For the large benchmark, with 5M elements, the total size of the data is 20MB (5M floating point = 5M * 4 bytes = 20MB). The total bandwidth usage for the allreduce_ring_chunked algorithm for 2 nodes is also about 20MB. At 1Gb/sec it takes 180ms to transfer 20MB. Your benchmark result is very close to that, so it looks correct.

Do you have any other interfaces in this machine? I recall seeing an interface named "ib0", which would indicate InfiniBand?

2. Fresh results with 2 nodes, 40GbE

       Device:      tcp, pci=0000:01:00.0, iface=eth0
       Algorithm:   allreduce_ring_chunked
       Options:     processes=2, inputs=1

       elements   min (us)   p50 (us)   p99 (us)   max (us)    samples
            100         75        143        192        234       7404
            200         87        132        160        191       7649
            500         92        142        172        203       5298
           1000         76        125        159        187       7221
           2000         99        128        153        179       6389
           5000        106        132        148        170       6769
          10000         95        126        151        174       5931
          20000        116        146        175        199       5383
          50000        197        247        279        313       4217
         100000        325        372        415        461       2452
         200000        490        514        646        790       1113
         500000        967       1217       1424       1553        553
        1000000       1697       1993       2133       2416        394
        2000000       4217       5510       6301       6617        168
        5000000      12567      14699      15509      16830         79

3. The `--iteration-time` argument specified how long to run every iteration. This is why with higher element counts you'll have fewer runs (samples).

**Comment by pietern** [comment]
By the way, I think it would be nice to also include the link speed in the benchmark output, so we can easily compare numbers without having that be specified separately. So taking that as a feature request :)

**Comment by pietern** [comment]
Closing this issue, as it looks like this is now resolved. We can keep chatting though :)

**Comment by linquanxu** [comment]
I really appreciate your answer to my questions. @pietern , I also have tested on the InfiniBand (40Gb/s, 2 nodes).
![image](https://cloud.githubusercontent.com/assets/16631303/24902348/772370de-1edc-11e7-82b5-bec77aa259e2.png)

**Comment by linquanxu** [comment]
I close this issue now. Thanks again for your help.

**Comment by pietern** [comment]
@linquanxu If the IB speed is lower, can you pull the latest code and open a new issue with the full output of the benchmark (so it includes the link information)? Thanks.
