### ISSUE TITLE
Why CUDA benchmark doesn't include allreduce_ring?

### ISSUE THREAD

**Issue by leeQT** [facebookincubator/gloo#222]
The ordinary version of benchmark supports allreduce_ring but CUDA version doesn't. However in the source code there is CUDA implementation of it. Is it because allreduce_ring doesn't perform well on CUDA?

**Comment by pietern** [comment]
The regular ring algorithm is only useful for very tiny messages (since it puts more bytes on the wire compared to the chunked version), so this was never added for CUDA.

**Comment by leeQT** [comment]
> The regular ring algorithm is only useful for very tiny messages (since it puts more bytes on the wire compared to the chunked version), so this was never added for CUDA.

But there is gloo/gloo/cuda_allreduce_ring.cc and  gloo/gloo/cuda_allreduce_ring.h.
