### ISSUE TITLE
Potential overflow issue in tcp/pair.cc

### ISSUE THREAD

**Issue by rohan-varma** [facebookincubator/gloo#256]
This line https://github.com/facebookincubator/gloo/blob/master/gloo/transport/tcp/pair.cc#L896 uses `timeout_ * 5`, but passing this into `cv.wait_for` could potentially overflow if the `timeout_` is very large, as the docs for `wait_for` (https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for) state that "rel_time must be small enough not to overflow when added to std::chrono::steady_clock::now().". Thus, we could potentially timeout immediately while connecting, which is an issue.

**Comment by osalpekar** [comment]
Offending line is now at https://github.com/facebookincubator/gloo/blob/master/gloo/transport/tcp/pair.h#L313. We could clamp `rel_time` to be maximum of (std::chrono::milliseconds::max - std::chrono::steady_clock::now()).
