### ISSUE TITLE
Enable Gloo working on windows platform, libuv as transport

### ISSUE THREAD

**Issue by gunandrose4u** [facebookincubator/gloo#263]
## 🚀 Feature
Enable Gloo working on windows platform, for the first step, just make it working with libuv as transport.

1. Function broadcast and all_reduce supported on CPU and GPU
2. Gloo backend supported only, for Gloo, libuv supported only first
3. torch.nn.parallel.DistributedDataParallel() supported 
4. Shared file-system init_method supported only

## Motivation
Want to enable torch.distributed package of PyTorch working windows, at first step, just want to support Gloo as backend first. 

## How to do it
1. Add MSVC to detect whether compiling for windows platform
2. Force to use libuv as transport way
3. Exclude src directories, mpi, nccl, transport/tcp, transport/ibverbs
4. Disable compile option like USE_REDIS_DEFAULT, USE_IBVERBS_DEFAULT etc.
5. Add libuv library (build for windows platform)
6. Add a new example to show all_reduce function and libuv as transport since currently example is leverage tcp as transport
7. Port unsupported gloo source code to MSVC
8. Port unsupported gloo/cuda* source code to MSVC
9. Port test case and bench mark related to all_reduce and broadcast function to MSVC

## Example
    #include <iostream>
    #include <memory>
    #include <array>
    #include <typeinfo>

    #include "gloo/allreduce.h"
    #include "gloo/allreduce_ring.h"
    #include "gloo/rendezvous/context.h"
    #include "gloo/rendezvous/file_store.h"
    #include "gloo/rendezvous/prefix_store.h"
    #include "gloo/transport/uv/device.h"

    void mysum(void* c_, const void* a_, const void* b_, long unsigned int n) {
        printf("n=%d\r\n", n);
        int* c = static_cast<int*>(c_);
        const int* a = static_cast<const int*>(a_);
        const int* b = static_cast<const int*>(b_);
        for (auto i = 0; i < n; i++) {
            printf("a[%d]=%d\r\n", i, a[i]);
            printf("b[%d]=%d\r\n", i, b[i]);
            c[i] = a[i] + b[i];
            printf("c[%d]=%d\r\n", i, c[i]);
            
        }
    }

    int main(void) {
    // Unrelated to the example: perform some sanity checks.
        if (getenv("PREFIX") == nullptr ||
            getenv("SIZE") == nullptr ||
            getenv("RANK") == nullptr) {
            std::cerr
            << "Please set environment variables PREFIX, SIZE, and RANK."
            << std::endl;
            return 1;
        }

        gloo::transport::uv::attr attr;
        attr.ai_family = AF_UNSPEC;

        std::cout << "CreateDevice" << std::endl;
        auto dev = gloo::transport::uv::CreateDevice(attr);
        
        auto fileStore = gloo::rendezvous::FileStore("/libtmp");
        std::cout << "FileStore" << std::endl;

        std::string prefix = getenv("PREFIX");
        auto prefixStore = gloo::rendezvous::PrefixStore(prefix, fileStore);
        std::cout << "prefixStore" << std::endl;

        const int rank = atoi(getenv("RANK"));
        const int size = atoi(getenv("SIZE"));
        auto context = std::make_shared<gloo::rendezvous::Context>(rank, size);
        try {
            context->connectFullMesh(prefixStore, dev);
            std::cout << "connectFullMesh" << std::endl;
            std::array<int, 4> data;
            std::cout << "Input: " << std::endl;
            for (int i = 0; i < data.size(); i++) {
                data[i] = i;
                std::cout << "data[" << i << "] = " << data[i] << std::endl;
            }
            
            std::vector<int*> ptrs;
            ptrs.push_back(&data[0]);

            int count = data.size();
            size_t elements = 10;
            int inputs = 4;

            // Generate vectors with pointers to populate the options struct.
            std::vector<int*> inputPointers;
            std::vector<int*> outputPointers;
            for (size_t i = 0; i < elements; i++) {
            int *value = (int*)malloc(sizeof(int));
            *value = i * (rank + 1);
            printf("inputPointers jozh ptr %p\r\n", value);
            inputPointers.push_back(value);
            int *value1 = (int*)malloc(sizeof(int));
            *value1 = 0;
            printf("outputPointers jozh ptr %p\r\n", value1);
            outputPointers.push_back(value1);
            }
            
            
            // Configure AllreduceOptions struct
            gloo::AllreduceOptions opts_(context);
            opts_.setInputs(inputPointers, 1);
            opts_.setOutputs(outputPointers, 1);
            opts_.setAlgorithm(gloo::AllreduceOptions::Algorithm::RING);
            void (*fn)(void*, const void*, const void*, long unsigned int) = &mysum;
            opts_.setReduceFunction(fn);
            gloo::allreduce(opts_);

            std::cout << "Output: " << std::endl;
            for (int i = 0; i < outputPointers.size(); i++) {
            std::cout << "data[" << i << "] = " << *outputPointers[i] << std::endl;
            }
        }
        catch (const std::exception &exc)
        {
            std::cerr << exc.what();
        }

        return 0;
    }

**Comment by nbcsm** [comment]
https://github.com/facebookincubator/gloo/pull/264

**Comment by chauhang** [comment]
PR for libuv support has been merged: https://github.com/facebookincubator/gloo/commit/881f7f0dcf06f7e49e134a45d3284860fb244fa9

**Comment by gunandrose4u** [comment]
Close by PR https://github.com/facebookincubator/gloo/pull/264
