### ISSUE TITLE
Connection Refused error while running test_cuda

### ISSUE THREAD

**Issue by talk2ap001** [facebookincubator/gloo#33]
The **test_cuda** sample provided with gloo gives the following error occasionally, when run multiple times. (Running on 1 machine with 2 GPUs)
```
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/sayantan/gloo_GIT/gloo/gloo/transport/tcp/pair.cc:498] optval == 0. 111 vs 0. SO_ERROR: Connection refused
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 29013 on node 172.17.27.12 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```
Alternatively, I get this error at times:
```
unknown file: Failure
C++ exception with description "[/home/sayantan/gloo_GIT/gloo/gloo/transport/tcp/pair.cc:135] bind: Address already in use" thrown in the test body.
[mAllreduceHalvingDoublingPipelined/CudaAllreduceTest.MultiPointerAsync/14, where GetParam() = (32, 64, 32-byte object <80-C9 28-03 00-00 00-00 B8-EA 2A-03 00-00 00-00 D0-BA 4B-00 00-00 00-00 60-B8 4B-00 00-00 00-00>)
```
And at times it succeeds.

Log files:
[Failure_1node_1.txt](https://github.com/caffe2/caffe2/files/954811/Failure_1node_1.txt)
[Failure_1node_2.txt](https://github.com/caffe2/caffe2/files/954812/Failure_1node_2.txt)
[Failure_1node_3.txt](https://github.com/caffe2/caffe2/files/954813/Failure_1node_3.txt)

(Moved this issue here from https://github.com/caffe2/caffe2/issues/360 as it seems to be more appropriate)

UPDATED:
[Stacktrace_GDB.txt](https://github.com/caffe2/caffe2/files/958173/Stacktrace_GDB.txt)

**Comment by pietern** [comment]
Thanks for reporting this @talk2ap001, and I'll take a look at the C2 issue as well.

Are you running test_cuda through mpirun? It's doesn't expect that to be the case, nor does it use any MPI functions, so running with for example `-np 2` means you'll just run the test suite twice (in parallel).

The errors that you experience are likely one and the same. If there's multiple threads being used for a test case, any of them might be first in reporting an error, if they see one. So whereas one process might fail to bind to an address, another might get a connection refused trying to connect to that process. This is a first hunch though, have to double check if this is even possible.

**Comment by pietern** [comment]
And to be able to debug this better, let me add some extra information to the error.

**Comment by talk2ap001** [comment]
Thanks Pieter. Yes, initially I ran test_cuda with mpirun on different machines and it spawned correctly (but produced the same error). I figured that it may not be meant to be run with mpi and that would just launch same test_cuda on different machines, since I'm not providing any rendezvous path, for example.

Then, running them locally as ./test_cuda gives the same error. 

I suspect this issue could be fundamental to resolving the Caffe2 issue that I'm having. Thanks once again for helping out.

**Comment by pietern** [comment]
The tests work fine for me. Since the error happens in the exact same test every time, this might be related to some operating system level limit we're hitting. Maybe number of ephemeral IP ports, or number of file descriptors, or something along those lines. Could you take a look at your kernel logs (or dmesg) and see if anything stands out?

**Comment by talk2ap001** [comment]
Hi @pietern. I checked the /var/log and the apport.log reports an error upon failure of test_cuda. After increasing the core file size the cored dump also got generated.

I've cloned the latest gloo and compiled with symbols. The error that I now get is this:
```
...
unknown file: Failure
C++ exception with description "[/home/sayantan/gloo_GIT2/gloo/gloo/transport/tcp/pair.cc:125] bind: Address already in use" thrown in the test body.
[  FAILED  ] AllreduceRing/CudaAllreduceTest.SinglePointer/24, where GetParam() = (8, 4, 32-byte object <80-DC 08-02 00-00 00-00 28-E2 08-02 00-00 00-00 F0-B8 4B-00 00-00 00-00 D0-B4 4B-00 00-00 00-00>) (30081 ms)
[ RUN      ] AllreduceRing/CudaAllreduceTest.SinglePointer/25
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/sayantan/gloo_GIT2/gloo/gloo/transport/tcp/pair.cc:592] fd_ == FD_INVALID. 27 vs -1. File descriptor not closed
Aborted (core dumped)
```

From core dump and gdb, I extracted the full stack-trace for this, please have a look:
[StackTrace_CoreDump_Full.txt](https://github.com/facebookincubator/gloo/files/960943/StackTrace_CoreDump_Full.txt)

**Comment by pietern** [comment]
I don't think this is a threading problem, but that some error in the destruction path is masking the *real* error. Checking out how we can fix the surface error, so we can unmask the real one...

**Comment by pietern** [comment]
Many thanks for the detailed reports!

**Comment by pietern** [comment]
I've seen it a few times now as well, after running the test suite a couple of times in a row. I'm pretty sure it can't bind to a local address because the machine runs out of ephemeral ports. We should be setting `SO_REUSEPORT` and/or `SO_REUSEADDR` on the sockets we create to allow the OS to clean them up quickly. Patch incoming.

**Comment by pietern** [comment]
If you see this error again, you can run `netstat -nt | grep TIME_WAIT | wc -l` to keep an eye on the number of connections in the `TIME_WAIT` state. I expect this to be high. I've seen it at >40k when seeing the error myself. Other than the fixes I just pushed there is little we can do about this state, aside from retrying and backing off. Since this only happens in tests, I think we can treat the errors as benign and ignore them.
