### ISSUE TITLE
error: aggregate ‘std::array<char, 64> hostname’ has incomplete type and cannot be defined

### ISSUE THREAD

**Issue by Bidski** [facebookincubator/gloo#332]
Trying to build gloo via pytorch ([this commit](https://github.com/facebookincubator/gloo/tree/c22a5cfba94edf8ea4f53a174d38aa0c629d070f)) and receiving this error
```
pytorch/third_party/gloo/gloo/transport/tcp/device.cc: In function ‘gloo::transport::tcp::attr gloo::transport::tcp::CreateDeviceAttr(const attr&)’:
pytorch/third_party/gloo/gloo/transport/tcp/device.cc:151:39: error: aggregate ‘std::array<char, 64> hostname’ has incomplete type and cannot be defined
  151 |       std::array<char, HOST_NAME_MAX> hostname;
      |                                       ^~~~~~~~
```

Adding `#include <array>` to the top of `gloo/transport/tcp/device.cc` resolves the error

**Comment by Bidski** [comment]
Looks like [this commit](https://github.com/facebookincubator/gloo/commit/7b58938c5d87380f88a5266035dda1041d45626e) may have introduced this bug

**Comment by hmaarrfk** [comment]
```patch
diff --git a/gloo/transport/tcp/device.cc b/gloo/transport/tcp/device.cc
index 05cf0a4..6aa48f5 100644
--- a/gloo/transport/tcp/device.cc
+++ b/gloo/transport/tcp/device.cc
@@ -12,6 +12,7 @@
 #include <netdb.h>
 #include <netinet/in.h>
 #include <string.h>
+#include <array>
 
 #include "gloo/common/linux.h"
 #include "gloo/common/logging.h"
diff --git a/gloo/transport/tcp/tls/pair.cc b/gloo/transport/tcp/tls/pair.cc
index 176fa5e..bf39bbf 100644
--- a/gloo/transport/tcp/tls/pair.cc
+++ b/gloo/transport/tcp/tls/pair.cc
@@ -17,6 +17,7 @@
 
 #include <cstring>
 #include <poll.h>
+#include <array>
 
 namespace gloo {
 namespace transport {
```
Seems like it addresses thing.

**Comment by xgupta** [comment]
> Does anyone know why the associated PR #333 was closed? This seems like the kind of thing that should have been fixed the moment it was reported. It's a one-line fix

Not sure, I commit is already made to fix the issue - https://github.com/facebookincubator/gloo/commit/4a5e339b764261d20fc409071dc7a8b8989aa195.

**Comment by xgupta** [comment]
Okay to close this issue?
