### ISSUE TITLE
CMakeList.txt is missing types.h in GLOO_HDRS

### ISSUE THREAD

**Issue by colesbury** [facebookincubator/gloo#37]
https://github.com/facebookincubator/gloo/blob/f5d919a685889f538883581b324eaaf03a088809/gloo/CMakeLists.txt#L24

**Comment by pietern** [comment]
cc @wesolwsk -- can you add this one?

**Comment by pietern** [comment]
Thanks for reporting @colesbury. We really need to add some post-install compilation test. We have run into a missing header post-install before...

**Comment by pietern** [comment]
Fixed in 2486a6bbd0cbccffd682a4d5340abcf1016fe7d3
