### ISSUE TITLE
error when running with ibverbs

### ISSUE THREAD

**Issue by hfutxrg** [facebookincubator/gloo#52]
Hi All,
I just pulled the latest Gloo repo and try to use TCP and ibvers transport. The TCP approach is working well, but ibverbs is not working. Could someone tell me whether I did anything wrong or there is any bug in gloo library?

I have two servers: ubuntu01 and ubuntu02. Those two servers are connected by 100Gb/s EDR Infiniband. The IPv4 of two servers are 192.168.254.217 and 192.168.254.218. The IPoIB of two servers are 10.149.0.1 and 10.149.0.2. Here ubuntu01 is used as redis server and ubuntu02 is used as redis client.

First I run `redis-server redis.conf` on ubuntu01. The following are the configurations in redis.conf
`bind 192.168.254.217 10.149.0.1`
`protected-mode no`
`daemonize yes`

Then I compile gloo with `-DUSE_IBVERBS=1 -DBUILD_TEST=1 -DBUILD_BENCHMARK=1`
Then I run benchmark on both servers:
on ubuntu01:
`./benchmark --size 2 --rank 0 --redis-host 10.149.0.1 --redis-port 6379 --prefix 1303 --transport ibverbs --elements -1 allreduce_ring_chunked`

on ubuntu02:
`./benchmark --size 2 --rank 1 --redis-host 10.149.0.1 --redis-port 6379 --prefix 1303 --transport ibverbs --elements -1 allreduce_ring_chunked`

But both nodes have the errors:
**terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /home/rengan/gloo/gloo/transport/ibverbs/pair.cc:466] wc->status == IBV_WC_SUCCESS. 12 vs 0. Memory region send for slot 0: transport retry counter exceeded
Aborted (core dumped)**

Does anyone have this error before and know how to fix it? Thanks.

Regards,
Rengan

**Comment by pietern** [comment]
Thanks for posting the report! I ran into the same issue last week as well. I found a fix for this this morning and it's available in #53. I'm running the benchmark the exact same way you do and it now works. The fix will be merged asap and then you can simply pull the latest code and try again.

**Comment by pietern** [comment]
Merged in 6bd3621b68800eb542c83fff3b10199713d7ffda.

**Comment by hfutxrg** [comment]
Thanks @pietern. It works perfectly now.
