### ISSUE TITLE
[Question] creating an ibverbs context, or any context

### ISSUE THREAD

**Issue by Luo-Liang** [facebookincubator/gloo#65]
Hi! I'm very interested in trying out Gloo but I'm pretty new so the question may be dumb:

I'm trying to integrate Gloo into my code and it seems all algorithms require a context object. I am attempting to create such a context with infiniband devices...

    gloo::transport::ibverbs::attr verbsAttr;
    verbsAttr.name = "mlx4_0";
    dev = CreateDevice(verbsAttr);
    gloo::Context context = ???

Any pointer is appreciated. Thank you!

**Comment by pietern** [comment]
Hi!

You can create a context directly and then have to connect all participating process through a rendezvous phase. You can read more about this in [docs/rendezvous.md](https://github.com/facebookincubator/gloo/blob/master/docs/rendezvous.md). You can use either a shared filesystem (e.g. NFS), Redis, or MPI to perform rendezvous.
