### ISSUE TITLE
hostname issue in Gloo

### ISSUE THREAD

**Issue by hfutxrg** [facebookincubator/gloo#70]
Hi All,

By checking Gloo code, I found Gloo first finds the hostname of a server by using gethostname() function, and then get the corresponding network interface. However, the default hostname on my server is an Ethernet address. I want to use the hostname which is an IPoIB address but it never succeeds. 

For instance, the default hostname on my node is node001 which corresponds to Ethernet address, but I want to use the hostname node001.ib.cluster which corresponds to the IPoIB address. My current solution is to change the hostname in /proc/sys/kernel/hostname, but this requires root permission. 

So my questions are:
1. Where does gethostname()  exactly fetch the hostname?
2. Is there any way to use a different hostname to use IPoIB instead of Ethernet address?

Thanks.
Rengan

**Comment by pietern** [comment]
Hi! You can override which hostname it uses by setting the `hostname` field on `gloo::transport::tcp::attr` to either the hostname you use for your IPoIB interface, or the IP address assigned to it.

`gethostname()` uses the system hostname, see the [man page for gethostname(2)](http://man7.org/linux/man-pages/man2/gethostname.2.html)

**Comment by hfutxrg** [comment]
Hi @pietern , I think it is not useful to change the hostname in attr struct. Because multiple nodes need to use its own hostname. We cannot use a fixed hostname for all nodes. Any other solutions?

**Comment by pietern** [comment]
It depends, how/where are you using Gloo?

**Comment by hfutxrg** [comment]
I am using Caffe2 which uses Gloo for node communication.

**Comment by pietern** [comment]
Ah I see. We can do one of two things: either add an option to the Caffe2 bindings to set the hostname, or we can add an option to the TCP transport to specify an interface, or both of course.

Is this something you're willing to contribute?

**Comment by hfutxrg** [comment]
Hi @pietern, sure I would like to contribute. I think it's better to use an environment variable like GLOO_INTERFACE for Gloo so that we don't need to change Caffe2 code. I will try that to see whether it works or not.

**Comment by pietern** [comment]
I think adding the interface itself will be a valuable addition as well. Adding it to Gloo first, then Caffe2.

**Comment by pietern** [comment]
See 7def89c590beabd9573e6dee62ac770b3c3f64bd for Gloo support.

You can now specify the interface to use by doing:
```
gloo::transport::tcp::attr attr;
attr.iface = name;
auto dev = gloo::transport::tcp::CreateDevice(attr);
```

I'm closing this issue, since Caffe2 support is separate. I'll comment back here when that has landed.
